name: Publish retronix.py to pypi.org
on:
   push:
      branches:
        - master
      paths:
        - '**.py'
        - '**.json'
jobs:
   build-n-publish:
      name: Build and publish to PyPi
      runs-on: ubuntu-18.04
      steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
           python-version: 3.7
      - name: Install pep517
        run: >-
           python -m pip install -u pep517
      - name: Build binary and tarball
        run: >-
        python -m pep517.buind --source --binary --out-dir dist/ .
      - name: Publish to pypi
        uses: pypa/gh-action-pypi-publish@master
        with:
           password: ${{secrets.pypi_password}}
           repository_url: https://pypi.org/legacy/
